codecov:
  require_ci_to_pass: yes
  bot: "codecov-bot"

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
        if_ci_failed: error
        
    patch:
      default:
        target: 80%
        threshold: 2%
        base: auto
        
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tests/**/*"
  - "examples/**/*"
  - "docs/**/*"
  - "vscode-extension/**/*"
  - "**/__init__.py"
  - "**/__main__.py"
  - "setup.py"