version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "cursor-eta/maintainers"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "cursor-eta/maintainers"
  
  # VS Code Extension npm dependencies
  - package-ecosystem: "npm"
    directory: "/vscode-extension"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "vscode-extension"
      - "javascript"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "cursor-eta/maintainers"
    ignore:
      # Ignore major version updates for VS Code API
      - dependency-name: "@types/vscode"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vscode"
        update-types: ["version-update:semver-major"]